# Generated by Django 2.2 on 2019-09-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_event_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Attendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_attendees_id', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Event_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category_id', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=50)),
                ('category_id', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(to='eventFinderApp.Category')),
                ('event', models.ManyToManyField(to='eventFinderApp.Event')),
            ],
        ),
    ]
